name: Build and push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build :latest
      run: docker build --file Dockerfile -t battlefleet:latest .

    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push battlefleet:latest